# Generated by Django 3.0.2 on 2020-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFileExtracter', '0002_auto_20200318_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='text',
            field=models.TextField(),
        ),
    ]
